/**
 * Uploads ALL SimpleNursing produced content to GitHub release
 * and adds every item to the Airtable "Produced Videos" table with a public link.
 *
 * Run: npx tsx src/scripts/airtable-produced-all.ts
 */
import 'dotenv/config'
import { stat } from 'fs/promises'
import { join, basename } from 'path'
import { existsSync } from 'fs'
import { spawn } from 'child_process'

const STUDIO_BASE = process.env.AIRTABLE_STUDIO_BASE ?? 'app4LEuOXBxPArLsr'
const STUDIO_KEY  = process.env.AIRTABLE_STUDIO_KEY  ?? process.env.AIRTABLE_API_KEY!
const REPO        = 'samcolibri/aistudio'
const RELEASE_TAG = 'simplenursing-assets-2026-05-01'
const TABLE_NAME  = 'Produced Videos'

const log = (msg: string) => console.log(msg)

// ── Airtable ──────────────────────────────────────────────────────────────────
async function at(path: string, method = 'GET', body?: object) {
  const res = await fetch(`https://api.airtable.com/v0${path}`, {
    method,
    headers: { Authorization: `Bearer ${STUDIO_KEY}`, 'Content-Type': 'application/json' },
    body: body ? JSON.stringify(body) : undefined,
  })
  const d = await res.json() as any
  if (!res.ok) throw new Error(`AT ${method} ${path}: ${JSON.stringify(d).slice(0, 200)}`)
  return d
}

async function getTableId(): Promise<string> {
  const meta = await at(`/meta/bases/${STUDIO_BASE}/tables`)
  const t = (meta.tables as any[]).find(t => t.name === TABLE_NAME)
  if (!t) throw new Error(`Table "${TABLE_NAME}" not found — run setup-produced.ts first`)
  return t.id
}

async function clearTable(tableId: string) {
  log('  🗑  Clearing existing records...')
  let offset: string | undefined
  do {
    const res = await at(`/${STUDIO_BASE}/${tableId}?${offset ? `offset=${offset}` : ''}`)
    const ids: string[] = res.records.map((r: any) => r.id)
    // Delete in batches of 10
    for (let i = 0; i < ids.length; i += 10) {
      const batch = ids.slice(i, i + 10)
      const qs = batch.map(id => `records[]=${id}`).join('&')
      await at(`/${STUDIO_BASE}/${tableId}?${qs}`, 'DELETE')
    }
    offset = res.offset
  } while (offset)
  log('  ✅ Table cleared')
}

async function addRecord(tableId: string, fields: Record<string, any>) {
  await at(`/${STUDIO_BASE}/${tableId}`, 'POST', { fields })
}

// ── GitHub ────────────────────────────────────────────────────────────────────
function run(cmd: string, args: string[]): Promise<string> {
  return new Promise((resolve) => {
    let out = ''
    const child = spawn(cmd, args, { stdio: 'pipe' })
    child.stdout?.on('data', d => out += d.toString())
    child.stderr?.on('data', () => {})
    child.on('close', () => resolve(out.trim()))
  })
}

async function ensureRelease() {
  const existing = await run('gh', ['release', 'view', RELEASE_TAG, '--repo', REPO, '--json', 'tagName'])
  if (existing.includes(RELEASE_TAG)) {
    log(`  ♻️  Release ${RELEASE_TAG} exists`)
    return
  }
  await run('gh', ['release', 'create', RELEASE_TAG,
    '--title', 'SimpleNursing AI Studio — All Assets',
    '--notes', 'All SimpleNursing brand assets + AI-produced content from AI Studio',
    '--repo', REPO,
  ])
  log(`  ✅ Created release ${RELEASE_TAG}`)
}

async function upload(filePath: string): Promise<string> {
  await run('gh', ['release', 'upload', RELEASE_TAG, filePath, '--clobber', '--repo', REPO])
  const name = encodeURIComponent(basename(filePath))
  return `https://github.com/${REPO}/releases/download/${RELEASE_TAG}/${name}`
}

// ── Content catalog ───────────────────────────────────────────────────────────
interface Item {
  name: string
  category: 'AI Generated' | 'Reference Asset' | 'Brand Video'
  channel: string
  filePath: string
  status: 'Final' | 'Draft'
  notes: string
  briefId?: string
}

async function catalog(): Promise<Item[]> {
  const items: Item[] = []

  // Only AI-produced videos — everything generated by AI Studio pipeline
  const aiVideos: { file: string; name: string; status: 'Final' | 'Draft'; notes: string }[] = [
    { file: 'student_omnihuman_qt.mp4',       name: '9 Classes TikTok — Student Girl + Female Voice (OmniHuman) ✨ BEST', status: 'Final', notes: 'Realistic nursing student girl (Flux Pro Ultra) + Sarah female voice (Fish Audio) → OmniHuman v1.5 24s talking head. Re-encoded for universal QuickTime/browser playback. Best version.' },
    { file: 'student_omnihuman_final.mp4',   name: '9 Classes TikTok — Student Girl + Female Voice (OmniHuman) w/ Logo', status: 'Final', notes: 'Realistic nursing student girl (Flux Pro Ultra photo) + Sarah female voice (Fish Audio) → OmniHuman v1.5 one-call 24s talking head. Has SimpleNursing logo overlay.' },
    { file: 'google_direct_final.mp4',       name: '9 Classes TikTok — Google Veo 3 Direct ✨ BEST',        status: 'Final', notes: 'Google Veo 3.0 direct API — 5 scenes with audio ON. Character speaks the exact script with natural lip sync, gestures, expressions. No fal.ai. Stitched 30s.' },
    { file: 'omnihuman_logo.mp4',            name: '9 Classes TikTok — OmniHuman (ByteDance) ✨',            status: 'Final', notes: 'ByteDance OmniHuman v1.5 — portrait + Fish Audio → one-pass talking head. Trained on 18K hours human motion. Best emotional consistency.' },
    { file: 'musetalk_logo.mp4',             name: '9 Classes TikTok — MuseTalk v1.5 on Veo3',               status: 'Final', notes: 'MuseTalk v1.5 lip sync applied to Veo3 motion video. Real-time high-fidelity lip sync.' },
    { file: 'kling_avatar_logo.mp4',         name: '9 Classes TikTok — Kling Avatar v2 Pro ✨',              status: 'Final', notes: 'Kling AI Avatar v2 Pro — portrait + Fish Audio → one-pass talking head. Purpose-built avatar model.' },
    { file: 'veo3_lipsync_logo.mp4',         name: '9 Classes TikTok — Veo3 + Sync-Lipsync + Logo',         status: 'Final', notes: 'Google Veo3 (fal.ai) 4×8s clips → sync-lipsync mouth sync → Fish Audio voice + SimpleNursing logo.' },
    { file: 'veo3_with_logo.mp4',            name: '9 Classes TikTok — Veo3 + Logo',                        status: 'Draft', notes: 'Google Veo3 (fal.ai) 4×8s clips stitched to 30s, Fish Audio voice, logo. No lip sync pass.' },
    { file: 'tiktok_final_kling.mp4',        name: '9 Classes TikTok — Kling v2 + Sync-Lipsync',            status: 'Final', notes: 'Kling v2 Master image-to-video + sync-lipsync. Custom Fish Audio voice. Remotion render.' },
    { file: 'tiktok_v3.mp4',                 name: '9 Classes TikTok — SadTalker v3',                       status: 'Draft', notes: 'Full-screen SadTalker talking head. Fish Audio voice baked in via Remotion.' },
    { file: 'tiktok_final_synclipsync.mp4',  name: '9 Classes TikTok — Static + Sync-Lipsync',             status: 'Draft', notes: 'Static face loop + sync-lipsync. Good lip sync, no head motion.' },
    { file: 'tiktok_final.mp4',              name: '9 Classes TikTok — First Voice Version',                status: 'Draft', notes: 'First version: Fish Audio voice + static Mike cartoon character.' },
    { file: 'tiktok_with_voice.mp4',         name: '9 Classes TikTok — Voice Only (No Talking Head)',       status: 'Draft', notes: 'Mike cartoon poses + narration. No lip sync.' },
  ]
  for (const v of aiVideos) {
    const fp = join('/Users/anmolsam/aistudio/output/rec0kxOAXZNsJvmwO', v.file)
    if (existsSync(fp)) items.push({ name: v.name, category: 'AI Generated', channel: 'TikTok', filePath: fp, status: v.status, notes: v.notes, briefId: 'rec0kxOAXZNsJvmwO' })
  }

  return items
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  log('\n📋 Getting Airtable table...')
  const tableId = await getTableId()
  log(`  Table ID: ${tableId}`)

  log('\n🗑  Clearing old records...')
  await clearTable(tableId)

  log('\n🚀 Ensuring GitHub release exists...')
  await ensureRelease()

  log('\n📁 Cataloging all content...')
  const items = await catalog()
  log(`  Found ${items.length} items total\n`)

  let uploaded = 0
  let failed = 0

  for (const item of items) {
    const s = await stat(item.filePath).catch(() => null)
    if (!s) { log(`  ⚠ Missing: ${item.filePath}`); continue }
    const sizeMb = (s.size / 1024 / 1024).toFixed(1)

    // Upload to GitHub for public link
    let githubUrl = ''
    try {
      process.stdout.write(`  📤 [${sizeMb}MB] ${item.name.slice(0, 60)}... `)
      githubUrl = await upload(item.filePath)
      process.stdout.write('✅\n')
      uploaded++
    } catch (err) {
      process.stdout.write(`⚠ upload failed\n`)
      failed++
    }

    // Add to Airtable
    await addRecord(tableId, {
      'Name':          item.name,
      'Type':          item.category,
      'Channel':       item.channel,
      'Status':        item.status,
      'Brief ID':      item.briefId ?? '',
      'File Size':     `${sizeMb} MB`,
      'GitHub URL':    githubUrl || undefined,
      'Date Produced': new Date().toISOString().slice(0, 10),
      'Notes':         item.notes,
    }).catch(err => log(`  ⚠ Airtable failed: ${err.message?.slice(0, 80)}`))
  }

  log(`\n🎉 Done! ${uploaded} uploaded, ${failed} failed`)
  log(`\n📋 Airtable: https://airtable.com/${STUDIO_BASE}`)
  log(`🔗 GitHub:   https://github.com/${REPO}/releases/tag/${RELEASE_TAG}`)
}

main().catch(console.error)
