/**
 * Sets up the "Produced Videos" table in the AI Studio Airtable base
 * and uploads all produced SimpleNursing videos to a GitHub release for shareable links.
 *
 * Usage: npx tsx src/scripts/setup-produced.ts
 */
import 'dotenv/config'
import { readdir, stat } from 'fs/promises'
import { join, basename } from 'path'
import { existsSync } from 'fs'
import { spawn } from 'child_process'

const STUDIO_BASE = process.env.AIRTABLE_STUDIO_BASE ?? 'app4LEuOXBxPArLsr'
const STUDIO_KEY  = process.env.AIRTABLE_STUDIO_KEY  ?? process.env.AIRTABLE_API_KEY!
const AT_BASE     = `https://api.airtable.com/v0/${STUDIO_BASE}`
const META_BASE   = `https://api.airtable.com/v0/meta/bases/${STUDIO_BASE}`

const log = (msg: string) => console.log(msg)

// ── Airtable helpers ──────────────────────────────────────────────────────────
async function atFetch(url: string, method = 'GET', body?: object) {
  const res = await fetch(url, {
    method,
    headers: { Authorization: `Bearer ${STUDIO_KEY}`, 'Content-Type': 'application/json' },
    body: body ? JSON.stringify(body) : undefined,
  })
  const data = await res.json() as any
  if (!res.ok) throw new Error(`Airtable ${method} ${url}: ${JSON.stringify(data).slice(0, 200)}`)
  return data
}

async function getOrCreateTable(name: string): Promise<string> {
  // List existing tables
  const meta = await atFetch(`${META_BASE}/tables`)
  const existing = (meta.tables as any[]).find(t => t.name === name)
  if (existing) {
    log(`  ♻️  Table "${name}" already exists (id: ${existing.id})`)
    return existing.id
  }

  log(`  📋 Creating table "${name}"...`)
  const created = await atFetch(`${META_BASE}/tables`, 'POST', {
    name,
    fields: [
      { name: 'Name',          type: 'singleLineText' },
      { name: 'Type',          type: 'singleSelect', options: { choices: [
        { name: 'AI Generated' }, { name: 'Reference Asset' }, { name: 'Brand Video' }
      ]}},
      { name: 'Channel',       type: 'singleSelect', options: { choices: [
        { name: 'TikTok' }, { name: 'YouTube' }, { name: 'Instagram' }, { name: 'Pinterest' }
      ]}},
      { name: 'Status',        type: 'singleSelect', options: { choices: [
        { name: 'Draft' }, { name: 'Final' }, { name: 'Published' }
      ]}},
      { name: 'Brief ID',      type: 'singleLineText' },
      { name: 'Duration',      type: 'singleLineText' },
      { name: 'File Size',     type: 'singleLineText' },
      { name: 'GitHub URL',    type: 'url' },
      { name: 'Date Produced', type: 'singleLineText' },
      { name: 'Notes',         type: 'multilineText' },
    ],
  })
  log(`  ✅ Table created: ${created.id}`)
  return created.id
}

async function addRecord(tableId: string, fields: Record<string, any>) {
  return atFetch(`${AT_BASE}/${tableId}`, 'POST', { fields })
}

// ── GitHub release + upload ───────────────────────────────────────────────────
async function createGitHubRelease(tag: string): Promise<void> {
  return new Promise((resolve) => {
    const child = spawn('gh', [
      'release', 'create', tag,
      '--title', `SimpleNursing AI Studio — Produced ${new Date().toLocaleDateString()}`,
      '--notes', 'AI-produced SimpleNursing videos. Generated by AI Studio pipeline (Veo3 + Fish Audio + Remotion).',
      '--repo', 'samcolibri/aistudio',
    ], { stdio: 'pipe' })
    child.on('close', () => resolve()) // ignore errors if release exists
  })
}

async function uploadToRelease(tag: string, filePath: string): Promise<string> {
  return new Promise((resolve) => {
    const child = spawn('gh', [
      'release', 'upload', tag, filePath, '--clobber',
      '--repo', 'samcolibri/aistudio',
    ], { stdio: 'pipe' })
    child.on('close', () => {
      const fileName = basename(filePath)
      resolve(`https://github.com/samcolibri/aistudio/releases/download/${tag}/${encodeURIComponent(fileName)}`)
    })
  })
}

// ── Scan produced videos ──────────────────────────────────────────────────────
interface ProducedVideo {
  name: string
  type: 'AI Generated' | 'Reference Asset' | 'Brand Video'
  channel: string
  briefId?: string
  filePath: string
  status: 'Draft' | 'Final'
  notes?: string
}

async function scanProducedVideos(): Promise<ProducedVideo[]> {
  const videos: ProducedVideo[] = []

  // 1. SimpleNursing.mp4 from Downloads (reference video)
  videos.push({
    name: 'SimpleNursing — Reference Video',
    type: 'Reference Asset',
    channel: 'TikTok',
    filePath: '/Users/anmolsam/Downloads/SimpleNursing.mp4',
    status: 'Final',
    notes: 'Original SimpleNursing brand video — used as style reference for AI Studio',
  })

  // 2. Brand videos from aistudio-assets
  const brandDir = '/Users/anmolsam/Downloads/aistudio-assets'
  const brandFiles = await readdir(brandDir)
  for (const f of brandFiles) {
    if (!f.endsWith('.mp4')) continue
    const channel = f.includes('vertical') || f.includes('TikTok') ? 'TikTok' : 'YouTube'
    videos.push({
      name: `SimpleNursing — ${f.replace(/_vertical|\.mp4/g, '').replace(/_/g, ' ')}`,
      type: 'Brand Video',
      channel,
      filePath: join(brandDir, f),
      status: 'Final',
      notes: 'Existing brand video from SimpleNursing asset library',
    })
  }

  // 3. Today's AI-generated videos from output
  const outputDir = '/Users/anmolsam/aistudio/output/rec0kxOAXZNsJvmwO'
  const finalVideos = [
    { file: 'tiktok_final_kling.mp4',   name: '9 Classes — Kling v2 + sync-lipsync (LATEST)', status: 'Final' as const },
    { file: 'tiktok_final.mp4',          name: '9 Classes — First TikTok with voice',            status: 'Draft' as const },
  ]
  for (const { file, name, status } of finalVideos) {
    const fp = join(outputDir, file)
    if (existsSync(fp)) {
      videos.push({
        name: `AI: ${name}`,
        type: 'AI Generated',
        channel: 'TikTok',
        briefId: 'rec0kxOAXZNsJvmwO',
        filePath: fp,
        status,
        notes: 'Brief: "9 Classes That Get You Into Nursing School". Fish Audio custom voice + Kling v2 motion + sync-lipsync.',
      })
    }
  }

  return videos
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  log('\n📋 Setting up "Produced Videos" table in AI Studio Airtable...')
  const tableId = await getOrCreateTable('Produced Videos')

  log('\n📁 Scanning all SimpleNursing videos...')
  const videos = await scanProducedVideos()
  log(`  Found ${videos.length} videos`)

  // Create GitHub release for AI-generated videos
  const releaseTag = `produced-${new Date().toISOString().slice(0, 10)}`
  log(`\n🚀 Creating GitHub release: ${releaseTag}`)
  await createGitHubRelease(releaseTag)

  log('\n📤 Adding records to Airtable...')
  for (const v of videos) {
    let githubUrl = ''

    // Only upload AI-generated finals to GitHub (not 100MB+ brand videos)
    if (v.type === 'AI Generated' && v.status === 'Final') {
      const s = await stat(v.filePath)
      if (s.size < 100 * 1024 * 1024) { // < 100MB
        log(`  📤 Uploading to GitHub: ${basename(v.filePath)}...`)
        githubUrl = await uploadToRelease(releaseTag, v.filePath)
        log(`  ✅ ${githubUrl}`)
      }
    }

    const s = await stat(v.filePath).catch(() => null)
    const fileSizeMb = s ? `${(s.size / 1024 / 1024).toFixed(1)} MB` : 'unknown'

    await addRecord(tableId, {
      'Name': v.name,
      'Type': v.type,
      'Channel': v.channel,
      'Status': v.status,
      'Brief ID': v.briefId ?? '',
      'File Size': fileSizeMb,
      'GitHub URL': githubUrl || undefined,
      'Date Produced': new Date().toISOString().slice(0, 10),
      'Notes': v.notes ?? '',
    }).catch(err => log(`  ⚠ Record failed: ${err.message?.slice(0, 80)}`))

    log(`  ✅ "${v.name}"`)
  }

  log(`\n🎉 Done! View in Airtable:`)
  log(`   https://airtable.com/${STUDIO_BASE}`)
  log(`\n   GitHub release:`)
  log(`   https://github.com/samcolibri/aistudio/releases/tag/${releaseTag}`)
}

main().catch(console.error)
